#!/bin/sh

uci set network.lan.ipaddr='192.168.0.240'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.gateway='192.168.0.1'
uci set network.lan.dns='8.8.8.8 8.8.4.4'
uci commit network

exit 0
